- name: Upload private key to remote servers
  hosts: all
  gather_facts: no
  become: yes
  vars:
    private_key_path: ""  # Path to your private key on the local machine
    remote_private_key_path: "/home/{{ ansible_user | default('ubuntu') }}/.ssh/githubKey"  # Destination path on remote server

  pre_tasks:
    - name: Check if private_key_file is set
      fail:
        msg: "The 'private_key_file' variable is required and must not be empty."
      when: private_key_file | length == 0
  tasks:
    - name: Copy private key to remote server
      ansible.builtin.copy:
        src: "{{ private_key_path }}"
        dest: "{{ remote_private_key_path }}"
        mode: '0600'
        owner: "{{ ansible_user | default('ubuntu') }}"
        group: "{{ ansible_user | default('ubuntu') }}"


    - name: Ensure private key has correct permissions on remote server
      ansible.builtin.file:
        path: "{{ remote_private_key_path }}"
        mode: '0600'
        owner: "{{ ansible_user | default('ubuntu') }}"
        group: "{{ ansible_user | default('ubuntu') }}"

    - name: Configure SSH for GitHub access
      ansible.builtin.blockinfile:
        path: "/home/{{ ansible_user | default('ubuntu') }}/.ssh/config"
        create: yes
        owner: "{{ ansible_user | default('ubuntu') }}"
        group: "{{ ansible_user | default('ubuntu') }}"
        mode: '0600'
        block: |
          # Specific settings for GitHub
          Host github.com
              HostName github.com
              User git
              IdentityFile ~/.ssh/githubKey


    - name: Add GitHub.com to known_hosts
      ansible.builtin.known_hosts:
        path: "/home/{{ ansible_user | default('ubuntu') }}/.ssh/known_hosts"
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan -t ed25519 github.com') }}"
        state: present

    - name: Change Git remote URL
      ansible.builtin.shell: git remote set-url origin git@github.com:Learnovia-egy/Ansible.git
      args:
        chdir: "{{ dir }}"
      become_user: "{{ ansible_user | default('ubuntu') }}"
