---

- hosts: all
#  gather_facts: yes
  become: true
  tasks:

  - name: install nginx & screen package
    package:
      name:
        - "{{ nginx_package }}"
        - "{{ screen_package }}"
      state: latest
      update_cache: yes
