name: Auto Pull on Master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH for Access
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Extract IPs from the inventory file and add them to known_hosts
          for host in $(grep -Eo '^[^#;]+(\.[^#;]+)(com|net)' inventory); do
            ssh-keyscan -H $host >> ~/.ssh/known_hosts
          done

      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
          echo {{ ansible_user }}

      - name: Pull Latest Code on Servers
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          for host in $(grep -Eo '^[^#;]+(\.[^#;]+)(com|net)' inventory); do
            ssh -i ~/.ssh/id_rsa {{ ansible_user }}@$host "cd /Ansible && git pull origin master"
          done
