name: Call Reusable Auto-Pull Workflow

on:
  push:
    branches:
      - "*"

jobs:
  auto-pull:
    uses: Learnovia-egy/org-workflows/.github/workflows/auto-pull.yml@main
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    with:
      commands: |
        php artisan migrate
        php artisan db:seed --class=PermissionSeeder
        php artisan db:seed --class=TranslationSeeder
        composer install