name: Call Reusable Auto-Pull Workflow

on:
  push:
    branches:
      - "*"

jobs:
  auto-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Check SSH_PRIVATE_KEY presence
        run: |
          if [[ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]]; then
            echo "SSH_PRIVATE_KEY is not available"
            exit 1
          else
            echo "SSH_PRIVATE_KEY is detected"
          fi
