name: Call Reusable Auto-Pull Workflow

on:
  push:
    branches:
      - "*"

jobs:
  auto-pull:
    uses: OmmrGAZAR315/Ansible/.github/workflows/auto-pull.yml@master3-b  # Reference the reusable workflow here
    secrets: # Specify the secrets to be used in the reusable workflow
      SSH_PRIVATE_KEY: ${{ SSH_PRIVATE_KEY }}
    with:
      commands: |
        php artisan migrate &&
        php artisan db:seed --class=PermissionSeeder &&
        php artisan db:seed --class=TranslationSeeder &&
        composer install
    
        
