name: Auto Pull on Master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup SSH for Access
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Extract IPs from the inventory file and add them to known_hosts
          for host in $(grep -Eo '^[^#;]+(\.[^#;]+)(com|net)' inventory); do
            ssh-keyscan -H $host >> ~/.ssh/known_hosts
          done

      - name: Pull Latest Code on Servers
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          while read -r line; do
            # Extract the host and ansible_user from each line in the inventory
            host=$(echo "$line" | grep -Eo '^[^ ]+')
            ansible_user=$(echo "$line" | grep -Eo 'ansible_user=[^ ]+' | cut -d'=' -f2)

            # If ansible_user is empty, set a default user (e.g., ubuntu)
            ansible_user=${ansible_user:-ubuntu}

            # Run SSH command to pull latest code
            ssh -i ~/.ssh/id_rsa $ansible_user@$host "cd /Ansible && git pull origin master"
          done < <(grep -E '^[^#;]' inventory)
