name: Auto-Pull Workflow

on:
  workflow_call:

jobs:
  auto-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Access SSH Private Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Using the SSH private key: $SSH_PRIVATE_KEY" # This will be masked in logs
