name: Call Reusable Auto-Pull Workflow

on:
  push:
    branches:
      - "*"

jobs:
  auto-pull:
    uses: OmmrGAZAR315/Ansible/.github/workflows/auto-pull.yml@master3-b
    secrets:
      ssh-key: ${{ secrets.TEST }}
    with:
      ssh-key: $ssh-key
