name: Call Reusable Auto-Pull Workflow

on:
  push:
    branches:
      - "*"

jobs:
  auto-pull:
    runs-on: ubuntu-latest
    steps:
      - with: # Set the secret as an input
      - secret: ${{ secrets }}
      - name: Print secrets
        run: |
          echo "Secrets:"
          echo "${secret}"
