name: Call Reusable Auto-Pull Workflow

on:
  push:
    branches:
      - "*"

jobs:
  auto-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Set secrets as environment variables
        with:
            super_secret1: ${{ secrets.SUPER_SECRET1 }}
            super_secret2: ${{ secrets.SUPER_SECRET2 }}
        run: |
          echo "super_secret1: $super_secret1"
          echo "super_secret2: $super_secret2"


