name: Call Reusable Auto-Pull Workflow

on:
  push:
    branches:
      - "*"

jobs:
  auto-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Set secrets as environment variables
        uses: ./.github/workflows/auto-pull.yml
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          commands: "echo 'Hello World'"


