name: Call Reusable Auto-Pull Workflow

on:
  push:
    branches:
      - "*"

jobs:
  auto-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Secrets:"
          echo "${SSH_PRIVATE_KEY}"

      - name: Call Auto-Pull Workflow
        uses: OmmrGAZAR315/Ansible/.github/workflows/auto-pull.yml@master3-b
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
