name: Call Reusable Auto-Pull Workflow

on:
  push:
    branches:
      - "*"

jobs:
  call-workflow-passing-data:
    uses: OmmrGAZAR315/Ansible/.github/workflows/auto-pull.yml@master3-b

    steps:
      - name: test
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Hello World $SSH_PRIVATE_KEY "
        

