name: Call Reusable Auto-Pull Workflow

on:
  push:
    branches:
      - "*"

jobs:
  auto-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Call Auto-Pull Workflow
        with: # Set the secret as an input
          secret: ${{ secrets }}
        run: echo "Calling Auto-Pull Workflow"

      - name: Print secrets
        run: |
          echo "Secrets:"
          echo "${secret}"
