name: Call Reusable Auto-Pull Workflow

on:
  push:
    branches:
      - "*"

jobs:
  auto-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action
        uses: actions/hello-world-javascript-action@v1 # specify an action to use
        with:
          super_secret1: ${{ secrets.SECRET_NAME1 }} # replace SECRET_NAME1 with the actual secret name
        env:
          super_secret2: ${{ secrets.SECRET_NAME2 }} # replace SECRET_NAME2 with the actual secret name

      - name: Run command
        run: echo "This is a custom run command"

