name: Auto Pull on Master

on:
  push:
    branches:
      - *

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH for Access
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Extract IPs from the inventory file and add them to known_hosts
          for host in $(grep -Eo '^[^#;]+(\.[^#;]+)(com|net)' inventory); do
            ssh-keyscan -H $host >> ~/.ssh/known_hosts
          done

      - name: Pull Latest Code on Servers
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          while read -r line; do
            # Extract the host and ansible_user from each line in the inventory
            host=$(echo "$line" | grep -Eo '^[^#;]+(\.[^#;]+)(com|net)')
            ansible_user=$(echo "$line" | grep -Eo 'ansible_user=[^ ]+' | cut -d'=' -f2)
            echo host=$host ansible_user=$ansible_user
            echo $GITHUB_REF | awk -F/ '{print $3}'
            ssh -i ~/.ssh/id_rsa $ansible_user@$host "cd /Ansible && git fetch && git reset --hard $(echo $GITHUB_REF | awk -F/ '{print $3}')" &
          done < <(grep -E '^[^\[#;]' inventory)
          wait
          echo "Code pulled on all servers"
          echo host=$host ansible_user=$ansible_user
