name: Call Reusable Auto-Pull Workflow

on:
  push:
    branches:
      - "*"

jobs:
  auto-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action
        with: # Set the secret as an input
          super_secret1: ${{ secrets }}
        env: # Or as an environment variable
          super_secret2: ${{ secrets }}
        run: |
            echo "Hello world!"
            echo "The super secret is ${{ super_secret1 }}"
            echo "The super secret is ${{ super_secret2 }}"
            echo "The super secret
    
