name: Call Reusable Auto-Pull Workflow

on:
  push:
    branches:
      - "*"

jobs:
  auto-pull:
    uses: OmmrGAZAR315/Ansible/.github/workflows/auto-pull.yml@master
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    with:
      commands: |
        ssh-key: ${{ SSH_PRIVATE_KEY }}
        php artisan migrate
        php artisan db:seed --class=PermissionSeeder
        php artisan db:seed --class=TranslationSeeder
        composer install
